### PR TITLE
Keyword Query Contributor Sample

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by lmarqs** [comment]
Hi @gamerson, how can I run these tests in my local env?
Is there a way for me to access Jenkins output?
Thanks in advance.

**Comment by gamerson** [comment]
Hey @lmarqs  you can run these tests locally by just going into the repo dir and do `./diff.sh`

**Comment by gamerson** [comment]
also it seems these failed source formatting.  So run `gw checkSourceFormatting` to see those errors

**Comment by lmarqs** [comment]
Hi @gamerson. I thank you for the tip.
I created [this PR](https://github.com/gamerson/liferay-blade-samples/pull/498) that contains additional changes (format source fix, README.md enhancement, and others), I think we can close this one.

**Pull request closed without merging**
