### PR TITLE
blade-436

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:72

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:test:72

**Comment by lawrence-lee** [comment]
ci:test:72

**Comment by lawrence-lee** [comment]
Hey @codyhoag, This pull should make sure all of our samples are deployable against 7.2 RC3. I'll update to GA1 once the dust settles

**Comment by lawrence-lee** [comment]
ci:test:72

**Comment by codyhoag** [comment]
thanks @lawrence-lee!

**Comment by lawrence-lee** [comment]
ci:test:72

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
