### PR TITLE
test7z

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/586. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
