### PR TITLE
Fix blade sample tests

### PR DESCRIPTION
**Pull request by lawrence-lee**
I didn't make sure the functional tests were running as part of 'check.' I also cleaned up the tests a bit. I'm still trying to figure out what's going on with the CI servers. As a temp workaround, you'll have to run build.sh locally.

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/143. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
