### PR TITLE
Actionable Dynamic Queries Sample

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
@gamerson This sample is good to go! Complete with integration tests
cc @jrao 

```
:apps:service-builder:adq:adq-api:compileTestJava NO-SOURCE
:apps:service-builder:adq:adq-api:processTestResources NO-SOURCE
:apps:service-builder:adq:adq-api:testClasses UP-TO-DATE
:apps:service-builder:adq:adq-api:test NO-SOURCE
:apps:service-builder:adq:adq-api:testIntegration SKIPPED
:apps:service-builder:adq:adq-api:check UP-TO-DATE
:apps:service-builder:adq:adq-service:compileTestJava NO-SOURCE
:apps:service-builder:adq:adq-service:processTestResources NO-SOURCE
:apps:service-builder:adq:adq-service:testClasses UP-TO-DATE
:apps:service-builder:adq:adq-service:test NO-SOURCE
:apps:service-builder:adq:adq-service:copyTestModules
:apps:service-builder:adq:adq-service:setUpTestableTomcat SKIPPED
:apps:service-builder:adq:adq-service:startTestableTomcat SKIPPED
:apps:service-builder:adq:adq-service:compileTestIntegrationJava
:apps:service-builder:adq:adq-service:processTestIntegrationResources NO-SOURCE
:apps:service-builder:adq:adq-service:testIntegrationClasses
:apps:service-builder:adq:adq-service:testIntegration
2018-05-22 21:15:45.479 INFO  [RMI TCP Connection(32)-10.50.0.99][BundleStartStopLogger:35] STARTED com.liferay.blade.adq.api_1.0.0 [601]
2018-05-22 21:15:57.215 INFO  [RMI TCP Connection(31)-10.50.0.99][BundleStartStopLogger:35] STARTED com.liferay.blade.adq.service_1.0.0 [602]
2018-05-22 21:16:08.053 INFO  [RMI TCP Connection(32)-10.50.0.99][BundleStartStopLogger:38] STOPPED com.liferay.blade.adq.api_1.0.0 [601]
2018-05-22 21:16:08.175 INFO  [RMI TCP Connection(33)-10.50.0.99][BundleStartStopLogger:38] STOPPED com.liferay.blade.adq.service_1.0.0 [602]
:apps:service-builder:adq:adq-service:stopTestableTomcat
:apps:service-builder:adq:adq-service:check
:apps:service-builder:adq:adq-web:compileTestJava NO-SOURCE
:apps:service-builder:adq:adq-web:processTestResources NO-SOURCE
:apps:service-builder:adq:adq-web:testClasses UP-TO-DATE
:apps:service-builder:adq:adq-web:test NO-SOURCE
:apps:service-builder:adq:adq-web:testIntegration SKIPPED
:apps:service-builder:adq:adq-web:check UP-TO-DATE
```

**Comment by gamerson** [comment]
nice!

**Pull request merged**
