### PR TITLE
investigate resource bundle override

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/54. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/096caa04~1...096caa04) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
