### PR TITLE
New pr with requested changes

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/15. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/d24d1cd~1...d24d1cd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/431. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/432. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
