### PR TITLE
7.1 blade sample changes

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
@gamerson we still need to merge that cherry-pick from yesterday. There are source formatting issues in this PR

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/495. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/55. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
