### PR TITLE
LPS-70749 make service builder merge existing portlet-model-hints.xml

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/127. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @AndyWu2015   Does this happen for brand new service builder projects that are created from the project template?

**Comment by AndyWu2015** [comment]
yes , I will sent a pr for fixing service-builder template also.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/38. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/cdbb2aa~1...cdbb2aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
