### PR TITLE
LPS-68088 Make sure the component is never assigned to itself

### PR DESCRIPTION
**Pull request by csierra**
/cc @sherlyliu

### CODE REVIEW

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/114. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/c71af6a~2...c71af6a) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by gamerson** [comment]
Thanks @csierra  merged here: https://github.com/liferay/liferay-blade-samples/commit/a4c72d667e9edf1f38631d8b8a915415eedc43e5

**Comment by csierra** [comment]
hey @gamerson... thanks to you and to @sherlyliu

**Comment by gamerson** [comment]
Absolutely, thanks @sherlyliu

**Pull request closed without merging**
