### PR TITLE
blade-447

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:72

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lawrence-lee** [comment]
@codyhoag, I wasnt able to find any references to this in the breaking changes doc

**Comment by codyhoag** [comment]
@lawrence-lee I'll check around and see if we can add something so others are aware

**Pull request merged**
