### PR TITLE
BLADE-285 add ext module project example

### PR DESCRIPTION
**Pull request by Camork**

### CODE REVIEW

**Comment by codyhoag** [comment]
@Camork this is awesome! Do you mind adding to the README so it follows the guidelines outlined here: https://github.com/liferay/liferay-blade-samples#sample-docs. More detail the better! I can also transfer that knowledge over to an Ext plugin tutorial later on. Thanks!

**Comment by Camork** [comment]
Hi @codyhoag , I updated this READEME with more details, can you take a look? thanks

**Comment by codyhoag** [comment]
Thanks, @Camork! At first glance, it's a very good start. Once this sample is merged, I'll go through the doc more thoroughly and reach out if I have any questions. Thanks again!

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/538. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
