### PR TITLE
PTR-95 Use OSGi manifest headers to aggregate resource bundles and ov…

### PR DESCRIPTION
**Pull request by jhinkey**
…erride an existing resource bundle service.

Here it is, Greg. I'm excited that we don't have to create resource bundle loader classes for this! 

cc/ @codyhoag

### CODE REVIEW

**Comment by gamerson** [comment]
hey @lawrence-lee   Do we have existing functional tests for this sample?

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
@gamerson Yes we do. in case this doesnt catch what its supposed to do

https://github.com/liferay/liferay-blade-samples/blob/7.1/liferay-workspace/tests/blade.samples.test/src/testFunctional/java/com/liferay/blade/samples/override/login/web/test/LoginWebResourceBundleOverrideTest.java

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @lawrence-lee  this failure seems unrelated.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/63. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/dad86384~1...dad86384) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
