### PR TITLE
change liferay-gradle to gradle

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
changed dirs on CI. jenkins retest

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
I didnt' see the linux test here.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/228. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/124bd16~1...124bd16) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
