### PR TITLE
Search Model Pre-Filter Contributor

### PR DESCRIPTION
**Pull request by lmarqs**

### CODE REVIEW

**Comment by lmarqs** [comment]
ci:test

**Comment by lmarqs** [comment]
ci:test:71

**Comment by lmarqs** [comment]
ci:test

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/516. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
