### PR TITLE
samples cleanup

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
made changes on CI so now we'll have to do a jenkins retest to get new results

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
Can we switch shiro to use `compileInclude` and get rid of the `-includeresource:` instruction?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/369. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/b2b8d0f~6...b2b8d0f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
