### PR TITLE
Replicate AngularJS projects

### PR DESCRIPTION
**Pull request by rafoli**

### CODE REVIEW

**Comment by rafoli** [comment]
Hey @gamerson , I got the following error during the phase _bundlesTest warsTest diff_:
screen shot 2017-08-16 at 17 14 06

There is a difference between MANIFEST.MF files (maven x gradle).

**Comment by gamerson** [comment]
looks like the maven is missing some bnd plugins maybe?  I'll have a look

**Comment by rafoli** [comment]
Fixed! :)

**Comment by rafoli** [comment]
@gamerson, could you please send me the log files for: http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/34/ ?

Thanks

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/192. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
