### PR TITLE
Better exception handling

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by gamerson** [comment]
@lawrence-lee latest master failed?

**Comment by lawrence-lee** [comment]
@gamerson `:downloadBundle FAILED` I think there's something wrong with the release server. in the latest-ci directories it contains DXP files instead of ce-portal

**Comment by lawrence-lee** [comment]
also, this works because of https://github.com/lawrence-lee/liferay-blade-samples/blob/2aa4636a1980c9c454e2c805c0a8511c1d79a624/liferay-workspace/tests/utils/src/main/java/com/liferay/blade/samples/integration/test/utils/BladeCLIUtil.java#L131

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
@gamerson All the tests passed! woohoo we're green again. I'll need to ping chas about an updated bundle of 7010

**Comment by lawrence-lee** [comment]
@gamerson I made an SF change. Let's make sure it passes before merging. Thanks!

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/362. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/035eccf~2...035eccf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
