### PR TITLE
Keyword Query Contributor Sample

### PR DESCRIPTION
**Pull request by lmarqs**

### CODE REVIEW

**Comment by lmarqs** [comment]
Hi @gamerson, I ran the script below and it looks like the Jenkins fault is not related to this PR or any module under the `extension` directory.

Can this PR be merged?

```.sh
#!/bin/bash
set -xe
repoDir=`pwd`
function buildAll() {
  cd "$repoDir"
  cd gradle/extensions
  ./../gradlew checkSourceFormatting clean assemble
  cd "$repoDir"
  cd maven/extensions
  mvn --fail-at-end clean package
  cd "$repoDir"
  cd liferay-workspace/extensions
  ./../gradlew checkSourceFormatting clean assemble
  cd "$repoDir"
  ./gradlew diff
}
buildAll
```

**Comment by lmarqs** [comment]
ci:test:71

**Comment by gamerson** [comment]
Thanks @lmarqs  for the sample!  It has been merged here: https://github.com/liferay/liferay-blade-samples/commit/07f4c9e2b13227fa26a4eeec0a9c1c4e433fbc1c

**Comment by gamerson** [comment]
Also merged to master as well.
https://github.com/liferay/liferay-blade-samples/commit/398dc26471b167563c2618c771b00786e6d0b7a0

**Comment by lmarqs** [comment]
Hi @gamerson.

It is good to contribute to the community.

I also create [this new sample](https://github.com/gamerson/liferay-blade-samples/pull/504) that complements the idea of filtering on liferay portal.

It is important to know the difference between a `KeywordQueryContributor` and a `ModelPreFilterContributor`.

Thank you.

**Pull request closed without merging**
