### PR TITLE
Replicateliferayworkspace

### PR DESCRIPTION
**Pull request by lawrence-lee**
new pull

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Yay it passed!

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/2. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/ff65dcc~3...ff65dcc) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/48. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/ff65dcc~3...ff65dcc) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by gamerson** [comment]
Hey Lawerene, I made a few changes and resent it here: https://github.com/gamerson/liferay-blade-samples/pull/48

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/44. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/ddaeb82~4...ddaeb82) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
