### PR TITLE
New build.sh

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/97. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
