### PR TITLE
SF JSP

### PR DESCRIPTION
**Pull request by lawrence-lee**
Changes to sourceformatter caused this to fail our tests

### CODE REVIEW

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
@gamerson, there's something wrong with the windows server. I'll need to do more debugging on it to figure out what's going on, but stoptestable tomcat gives an error and that causes the build to fail. But the actual tests are passing

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/17. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/4d739f1~1...4d739f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
