### PR TITLE
Blade Reluctant Service Override

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
hey @jhinkey, is there a particular order i'm supposed to deploy these bundles? The greedy service doesnt seem to show up anywhere.

**Comment by jhinkey** [comment]
The bundles depend on `blade.reluctant.service.reference` to define the service API. So deploy `blade.reluctant.service.reference` first.

To demonstrate overriding a reluctant service reference, deploy `blade.custom.service` and then deploy the .cfg or .config. Check that the reluctant portlet uses the custom service.

To demonstrate overriding a service that has a greedy policy, undeploy `blade.custom.service`, deploy `blade.greedy.service.reference` (check that the greedy portlet uses he default service), and deploy `blade.customer.service` (check that the greedy portlet uses the custom service).

**Comment by lawrence-lee** [comment]
Okay. great! i'll rework these functional tests and resubmit the pull

**Comment by lawrence-lee** [comment]
Jim and I need to rework samples for consistent testing, pull sent here https://github.com/jhinkey/liferay-blade-samples/pull/1

**Pull request closed without merging**
