### PR TITLE
fix config

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@lawrence-lee @chrisbryanboyd woo-hoo! css builder 2.0.2!

**Comment by lawrence-lee** [comment]
very cool! @gamerson did you make this change in the CI as well ?
0ec972a244c1f9697b6ad9a6ab59496ebab3e1a8

**Comment by gamerson** [comment]
@lawrence-lee  no i didn't

**Comment by gamerson** [comment]
@lawrence-lee  can you add a ticket for blade to update project templates with new css builder 2.0.2

**Pull request merged**
