### PR TITLE
Add some missing files

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by izaera** [comment]
@gamerson Oops! Some files got merged with conflicts. See https://github.com/gamerson/liferay-blade-samples/blob/master/gradle/apps/npm-deduplication-portlets/angular/angular-consumer-portlet/build.gradle for example :-(

**Comment by gamerson** [comment]
thanks Ivan for this note, I've fixed that now.  However, I'm having a new problem with the npm examples after your update.  Here is the error when I try to build the npm-angular-portlet

```
> Task :apps:npm:angular-npm-portlet:npmInstall
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/greg/dev/my repos/liferay-blade-samples/gradle/build/node/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:183
      throw er; // Unhandled 'error' event
```

Any ideas?

**Comment by izaera** [comment]
Hi @gamerson. Seems to be an error with npm in your local installation, because it is working for me. Try deleting your `package-lock.json` file and `node_modules` folder and run `gradle clean deploy` again and see it if fixes it.

However, I'm seeing that the samples are not working with 7.1. They seem to be tweaked for 7.0. Is that the expected target version?

**Comment by izaera** [comment]
OK, I was testing master, sorry...

Still, shouldn't master point to 7.1 better? 🤔

**Comment by izaera** [comment]
I have switched to 7.1 and it doesn't deploy either. It looks like dependencies are tailored for 7.0 :-(

**Pull request merged**
