### PR TITLE
blade-410

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
@gamerson, This looks good. Can you please merge to master and backport to 7.1.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/582. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/c5371218~1...c5371218) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
