### PR TITLE
Resolve build errors

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci retest

**Comment by christopherbryanboyd** [comment]
ci test

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/436. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
