### PR TITLE
ptr-95 override resource bundle using OSGi manifest headers only

### PR DESCRIPTION
**Pull request by jhinkey**
Hey Greg,

Carlos helped me confirm that you can override resource bundles using OSGi manifest headers. It's the safest way and has been simplified. I updated the blade sample that I tested successfully. 

FYI - I updated the docs too. https://github.com/sez11a/liferay-docs/pull/3934

@codyhoag - I haven't changed this sample's docs. 

Thanks

### CODE REVIEW

**Comment by gamerson** [comment]
hey @jhinkey  which versions of Liferay does this work in?

**Comment by jhinkey** [comment]
@gamerson it's in all the 7.x versions :-)

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @jhinkey  can you send this change on top of master?  Also make sure and run source formatter first.  Thanks!

**Comment by jhinkey** [comment]
OK

**Pull request closed without merging**
