### PR TITLE
71samplesfixes-2

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
@gamerson This is ready to merge... but I dont know how to fix these SF issues in the stream.

```:apps:sample-verifier:checkSourceFormattingPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8

Chaining on method 'getSymbolicName' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 57 (Checkstyle:ChainingCheck)
Chaining on method 'getType' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 70 (Checkstyle:ChainingCheck)
Chaining on method 'get' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 74 (Checkstyle:ChainingCheck)
Chaining on method 'of' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 125 (Checkstyle:ChainingCheck)
Exception in thread "main" java.lang.Exception: Found 4 formatting issues:
1: Chaining on method 'getSymbolicName' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 57 (Checkstyle:ChainingCheck)
2: Chaining on method 'getType' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 70 (Checkstyle:ChainingCheck)
3: Chaining on method 'get' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 74 (Checkstyle:ChainingCheck)
4: Chaining on method 'of' is allowed, but follow the styling described here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/chaining.markdown: ./src/main/java/com/liferay/blade/samples/verifier/VerifySample.java 125 (Checkstyle:ChainingCheck)
```

**Comment by lawrence-lee** [comment]
also, please merge to master and backport to 7.1

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/535. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/9d339174~2...9d339174) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
