### PR TITLE
BLADE-285 sf

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
Here's the source formatting errors 

https://gist.github.com/lawrence-lee/1ed5a3227bba2bd782da1e522decd101

**Comment by lawrence-lee** [comment]
@gamerson @Camork

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-blade-samples/pull/57. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/61388235~1...61388235) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
