### PR TITLE
lps-88036

### PR DESCRIPTION
**Pull request by lawrence-lee**
I guess this was a breaking change. https://dev.liferay.com/en/develop/reference/-/knowledge_base/7-1/breaking-changes#upgrade-considerations

### CODE REVIEW

**Comment by lawrence-lee** [comment]
If it looks good to you, i'll work on the project template

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
