### PR TITLE
LRDOCS-3496

### PR DESCRIPTION
**Pull request by dnebing**
Addition of the Spring MVC portlet war sample, mirrors functionality in blade.servicebuilder.web but uses Spring MVC

### CODE REVIEW

**Comment by codyhoag** [comment]
Is there any way we could get a README and Javadoc written for this sample once it's published? I could review once it's created, and then can transfer similar aspects of the docs to the Service Builder web sample, since they're similar.

An example of a fully documented sample is the [blade.controlmenuentry](https://github.com/liferay/liferay-blade-samples/tree/master/liferay-gradle/blade.controlmenuentry).

**Comment by dnebing** [comment]
Happy to, Cody, I’ll work on that tonight.

**Comment by codyhoag** [comment]
Thanks, Dave! 😃

**Comment by gamerson** [comment]
hey @dnebing could you remove the 'bndtools' and 'gradle' parts of this pull?  I'm going to be removing them today.

**Review by gamerson — CHANGES_REQUESTED** [review]
Sorry about the extra work for gradle that is going away

**Comment by dnebing** [comment]
Np, Wil doo tonight. No bndtools though, no bnd war impl.

**Comment by gamerson** [comment]
Gotcha yeah that was one of the reasons why I wanted to remove bndtools, it makes less and less sense, since blade samples are getting to hold more wars

**Comment by gamerson** [comment]
@dnebing @david-truong we should probably add war variants for mvc portlet as well

**Comment by dnebing** [comment]
I’ve added the readme markdown files, added missing Javadoc to the portlet class, and I also removed the gradle project per Greg’s request.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/dnebing/liferay-blade-samples/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
