### PR TITLE
Merge master tests to 2.x

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/363. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/f20cfe0~1...f20cfe0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
