### PR TITLE
pull-request-63

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by lawrence-lee** [comment]
ci:test:71

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@lawrence-lee @jhinkey  this has been merged now

**Comment by jhinkey** [comment]
Terrific! Thanks for merging the changes to the `overrides/login-web-resource-bundle-override` sample.

cc @codyhoag

**Pull request merged**
