### PR TITLE
Logging7.0

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
ci:test:70

**Comment by lawrence-lee** [comment]
@gamerson ready to go! I had to ignore tests that were only failing on CI, but passes locally for me. I think it has to do with the newer version of Chrome that's on centos

**Comment by gamerson** [comment]
thanks @lawrence-lee

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
