### PR TITLE
Blade Language Web Functional Tests

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
@gamerson The latest windows test will fail because i didnt exclude the arquillian tests from running. I'm going to restructure our test suite so I dont need to keep changing the jenkins configurations in the future.

**Comment by lawrence-lee** [comment]
@gamerson disregard that last message. this pull is good to go!

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/146. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
