### PR TITLE
JDBC/JNDI README updates

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@codyhoag , there are some source formatting issues? 

```:extensions:servlet:checkSourceFormattingPicked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8

/home/jenkins/.jenkins/workspace/liferay-blade-samples-pr-tester/gradle/extensions/servlet/README.markdown
Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: ./README.markdown expected:<...orkspace.
2. Go to `[${liferay_workspace_root}/modules` and clone this repository
3. Go to the root folder of this repository that you just cloned
4. Start up your Liferay bundle
5. Run `gradle deploy` and place the generated jar into `${liferay_home}/deploy` or if you have `blade` installed, run `blade deploy`
6. Sign in to Liferay as Administrator
7. Navigate to Control Panel -> Configuration -> Server Administration -> Log Levels -> Add Category
8. Configure `com.liferay.blade.samples.servlet.BladeServlet` and the log level to `INFO`
9. Access to `http://localhost:8080/o/blade/servlet]` You'll see "Hello ...> but was:<...orkspace.
2. Go to `[``${liferay_workspace_root}/modules``` and clone this repository
3. Go to the root folder of this repository that you just cloned
4. Start up your Liferay bundle
5. Run ```gradle deploy``` and place the generated jar into ```${liferay_home}/deploy``` or if you have ```blade``` installed, run ```blade deploy```
6. Sign in to Liferay as Administrator
7. Navigate to Control Panel -> Configuration -> Server Administration -> Log Levels -> Add Category
8. Configure ```com.liferay.blade.samples.servlet.BladeServlet``` and the log level to ```INFO```
9. Access to ```http://localhost:8080/o/blade/servlet``]` You'll see "Hello ...>
	at com.liferay.source.formatter.BaseSourceProcessor.processFormattedFile(BaseSourceProcessor.java:407)
	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:281)
	at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:533)
	at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:630)
	at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:68)
	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:114)
	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
:extensions:servlet:checkSourceFormatting FAILED
```

**Comment by codyhoag** [comment]
It appears the source formatting issues are related to the `gradle/extensions/servlet` sample's README. That's the first I've seen that README (or project). I've included the SF fixes for that as well in this PR. Hopefully that fixes the SF issues.

**Comment by lawrence-lee** [comment]
Sorry @codyhoag ! my mind's in a different place. I didnt even think to look at the specific error -_-'

**Comment by codyhoag** [comment]
No problem @lawrence-lee. It was an easy fix 😃

**Comment by lawrence-lee** [comment]
ci:retest

**Pull request merged**
