### PR TITLE
Windows max char limit

### PR DESCRIPTION
**Pull request by lawrence-lee**
I tested it and spaces in the path works. The issue we're running into is the length. Windows would not let me copy the file into the same directory and gave me the max length error

### CODE REVIEW

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by gamerson** [comment]
This failed for me with the following:

```
:tests:test

com.liferay.blade.tests.BladeTest > verifyServiceBuilderGradleTemplate FAILED
    java.lang.AssertionError at BladeTest.java:292

com.liferay.blade.tests.BladeTest > verifyPanelAppGradleTemplates FAILED
    java.lang.AssertionError at BladeTest.java:180

com.liferay.blade.tests.BladeTest > verifyControlMenuEntryGradleTemplates FAILED
    java.lang.AssertionError at BladeTest.java:142

com.liferay.blade.tests.BladeTest > verifyServiceWrapperGradleTemplate FAILED
    java.lang.AssertionError at BladeTest.java:361

com.liferay.blade.tests.BladeTest > verifyPortletProviderGradleTemplates FAILED
    java.lang.AssertionError at BladeTest.java:218

com.liferay.blade.tests.BladeTest > verifyMVCPortletGradleTemplates FAILED
    java.lang.AssertionError at BladeTest.java:161

10 tests completed, 6 failed
:tests:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tests:test'.
> There were failing tests. See the report at: file:///Users/greg/dev/my%20repos/liferay-blade-samples/liferay-workspace/tests/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Pull request closed without merging**
