### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by wodencafe** [comment]
ci:retest

**Comment by wodencafe** [comment]
ci:retest

**Comment by wodencafe** [comment]
jenkins retest

**Comment by wodencafe** [comment]
ci:retest

**Comment by wodencafe** [comment]
jenkins retest

**Comment by wodencafe** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/410. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/5beef7f~1...5beef7f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
