### PR TITLE
support doing diffs for wars

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
the failure on windows is now that tomcat thing.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/liferay/liferay-blade-samples/pull/82. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/3f22b39~13...3f22b39) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
