### PR TITLE
update tests for 7.0 GA7

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
@gamerson this pull is ready to go. can you please merge this, then create a 7.0 branch?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/478. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
